# 제 1 유형

> 데이터셋 : weather2.csv
* https://data.kma.go.kr/cmmn/static/staticPage.do?page=intro
* 2020년도 이화동(서울), 수영동(부산)의 시간단위 기온과 강수량

In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/weather/weather2.csv")

## Q1.
> 여름철(6월, 7월, 8월) 이화동이 수영동보다 높은 기온을 가진 시간대는 몇개인가?

In [2]:
df.head()

                  time  이화동강수  이화동기온  수영동강수  수영동기온
0  2020-01-01 00:00:00    0.1   -3.9    0.0    2.5
1  2020-01-01 01:00:00    0.0   -3.1    0.0    3.4
2  2020-01-01 02:00:00    0.0   -1.8    0.0    3.8
3  2020-01-01 03:00:00    0.0   -0.8    0.0    4.6
4  2020-01-01 04:00:00    0.0   -0.1    0.0    5.1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    8784 non-null   object
 1   이화동강수   8784 non-null   float64
 2   이화동기온   8784 non-null   float64
 3   수영동강수   8784 non-null   float64
 4   수영동기온   8784 non-null   float64
dtypes: float64(4), object(1)
memory usage: 343.2+ KB

In [6]:
df.time = pd.to_datetime(df.time)
df["month"] = [date.month for date in df.time]
df.head()

                 time  이화동강수  이화동기온  수영동강수  수영동기온  month
0 2020-01-01 00:00:00    0.1   -3.9    0.0    2.5      1
1 2020-01-01 01:00:00    0.0   -3.1    0.0    3.4      1
2 2020-01-01 02:00:00    0.0   -1.8    0.0    3.8      1
3 2020-01-01 03:00:00    0.0   -0.8    0.0    4.6      1
4 2020-01-01 04:00:00    0.0   -0.1    0.0    5.1      1

In [24]:
summer_df = df[df.month.isin([6,7,8])]

In [25]:
answer = len(summer_df[summer_df["이화동기온"] > summer_df["수영동기온"]])
print(answer)

1415

## Q2.
> 이화동과 수영동의 최대강수량의 시간대를 각각 구하여라.

In [53]:
print(df.loc[df["이화동강수"] == df["이화동강수"].max()].time.values)

['2020-09-30T09:00:00.000000000']

In [52]:
print(df.loc[df["수영동강수"] == df["수영동강수"].max()].time.values)

['2020-07-23T12:00:00.000000000']

# 제 2 유형

> 데이터셋
* https://www.kaggle.com/shubh0799/churn-modelling
* 고객의 신상정보 데이터를 통한 회사 서비스 이탈 예측 (종속변수: Exited)
* 평가지표: F1-score

In [121]:
import pandas as pd

train_df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/train.csv")
test_df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/test.csv")
submission_df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churn/submission.csv")

In [122]:
train_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,6842,15793491,Cherkasova,714,Germany,Male,26,3,119545.48,2,1,0,65482.94,0
1,8963,15607874,Keane,687,France,Male,38,0,144450.58,1,0,1,137276.83,0
2,7047,15737627,Rivero,589,Germany,Female,20,2,121093.29,2,1,0,3529.72,0
3,7503,15697844,Whitehouse,721,Spain,Female,32,10,0.00,1,1,0,136119.96,1
4,3439,15722404,Carpenter,445,France,Female,30,3,0.00,2,1,1,127939.19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,1607,15714080,Goliwe,566,Germany,Female,40,2,97001.36,2,1,0,154486.01,0
7995,7744,15741643,Chiang,777,Germany,Male,35,7,122917.69,1,1,1,76169.68,0
7996,4231,15566660,Cole,670,France,Female,41,10,0.00,3,1,0,81602.02,0
7997,8870,15733597,Y?an,669,France,Female,41,0,150219.41,2,0,0,107839.03,0
7998,523,15595766,Watts,527,Spain,Male,37,5,93722.73,2,1,1,139093.73,0

In [123]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7999 entries, 0 to 7998
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        7999 non-null   int64
 1   CustomerId       7999 non-null   int64
 2   Surname          7999 non-null   object
 3   CreditScore      7999 non-null   int64
 4   Geography        7999 non-null   object
 5   Gender           7999 non-null   object
 6   Age              7999 non-null   int64
 7   Tenure           7999 non-null   int64
 8   Balance          7999 non-null   float64
 9   NumOfProducts    7999 non-null   int64
 10  HasCrCard        7999 non-null   int64
 11  IsActiveMember   7999 non-null   int64
 12  EstimatedSalary  7999 non-null   float64
 13  Exited           7999 non-null   int64
dtypes: float64(2), int64(9), object(3)
memory usage: 875.0+ KB

In [124]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

def my_preprocess(df, target="train", encode_list=None):
    df.drop(["RowNumber", "CustomerId", "Surname"], axis=1, inplace=True)
    df = pd.get_dummies(df, columns=["Geography", "Gender"])
    if target == "train":
        # encoder1 = LabelEncoder()
        # encoder2 = LabelEncoder()
        scaler1 = MinMaxScaler()

        # df["Geography"] = encoder1.fit_transform(df["Geography"])
        # df["Gender"] = encoder2.fit_transform(df["Gender"])
        df = scaler1.fit_transform(df)
        # encode_list = [encoder1, encoder2, scaler1]
        encode_list = [scaler1]
        return df, encode_list
    
    elif target == "test":
        # encoder1 = encode_list[0]
        # encoder2 = encode_list[1]
        # scaler1 = encode_list[2]
        scaler1 = encode_list[0]
        
        # df["Geography"] = encoder1.transform(df["Geography"])
        # df["Gender"] = encoder2.transform(df["Gender"])
        df = scaler1.transform(df)

        return df
    
    return None

In [125]:
from sklearn.model_selection import train_test_split

X = train_df.drop("Exited", axis=1)
y = train_df["Exited"]
# train, validation split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, stratify=y, random_state=123)

In [126]:
# preprocess
X_train_processed, en_list = my_preprocess(X_train, target="train", encode_list=None)
X_valid_processed = my_preprocess(X_valid, target="test", encode_list=en_list)
test_processed = my_preprocess(test_df, target="test", encode_list=en_list)

In [127]:
# imbalance data processing
from imblearn.over_sampling import SMOTE
smote_sample = SMOTE(random_state=123)
X_train_smote, y_train_smote = smote_sample.fit_resample(X_train_processed, y_train)

In [128]:
corr = pd.DataFrame(X_train_smote).corr()
corr.style.background_gradient()

In [130]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

from sklearn.metrics import f1_score

* 로지스틱 회귀

In [131]:
model_logit = LogisticRegression(random_state=123)

model_logit.fit(X_train_smote, y_train_smote)
pred = model_logit.predict(X_valid_processed)

f1_score(y_valid, pred)

0.48624862486248627

* 랜덤 포레스트

In [132]:
score = []
for depth in range(5, 26):
    model_rf = RandomForestClassifier(max_depth=depth, random_state=123)

    model_rf.fit(X_train_smote, y_train_smote)
    pred = model_rf.predict(X_valid_processed)

    score.append(f1_score(y_valid, pred))

pd.DataFrame(score, index=range(5,26), columns=["f1"]).sort_values("f1")

          f1
5   0.557500
6   0.560701
10  0.562923
17  0.566616
7   0.569231
25  0.569640
9   0.571429
8   0.573684
23  0.574568
15  0.575301
18  0.578867
16  0.579666
20  0.581649
11  0.581818
24  0.583201
12  0.584527
21  0.586207
22  0.588419
19  0.588785
14  0.590504
13  0.591045

max_depth = 13 일때 가장 f1 스코어가 높음

In [134]:
model_rf = RandomForestClassifier(max_depth=13, random_state=123)
model_rf.fit(X_train_smote, y_train_smote)

print("훈련데이터의 f1 스코어")
print(f1_score(y_train_smote, model_rf.predict(X_train_smote)))

print("검증데이터의 f1 스코어")
print(f1_score(y_valid, model_rf.predict(X_valid_processed)))

훈련데이터의 f1 스코어
0.9693669162695712
검증데이터의 f1 스코어
0.591044776119403

* 그레디언트 부스팅

In [135]:
score = []
for depth in range(2, 8):
    model_boost = GradientBoostingClassifier(max_depth=depth, random_state=123)
    model_boost.fit(X_train_smote, y_train_smote)
    pred = model_boost.predict(X_valid_processed)
    score.append(f1_score(y_valid, pred))

pd.DataFrame(score, index=range(2,8), columns=["f1"]).sort_values("f1")

         f1
2  0.578313
7  0.598007
5  0.606852
3  0.607299
4  0.608424
6  0.613065

max_depth가 6일때 f1 스코어가 가장 높음

In [136]:
model_boost = GradientBoostingClassifier(max_depth=6, random_state=123)
model_boost.fit(X_train_smote, y_train_smote)

print("훈련데이터의 f1 스코어")
print(f1_score(y_train_smote, model_boost.predict(X_train_smote)))
print("검증데이터의 f1 스코어")
print(f1_score(y_valid, model_boost.predict(X_valid_processed)))

훈련데이터의 f1 스코어
0.9421751722760411
검증데이터의 f1 스코어
0.6130653266331657

* 서포트 벡터 머신

In [137]:
model_svm = SVC(kernel="rbf", C=0.1, random_state=123)
model_svm.fit(X_train_smote, y_train_smote)

print("훈련데이터 f1 스코어")
print(f1_score(y_train_smote, model_svm.predict(X_train_smote)))
print("검증데이터 f1 스코어")
print(f1_score(y_valid, model_svm.predict(X_valid_processed)))

훈련데이터 f1 스코어
0.7045431651052685
검증데이터 f1 스코어
0.4895104895104895

**그레디언트 부스팅의 성능이 가장 우수**

In [138]:
test_pred = model_boost.predict(test_processed)
submission_df["0"] = test_pred
submission_df.to_csv("submission_model.csv", index=False)